Traceback (most recent call last):
  File "models/main.py", line 8, in <module>
    import pandas as pd
  File "/home/joker/.local/lib/python3.5/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/home/joker/.local/lib/python3.5/site-packages/pandas/core/api.py", line 26, in <module>
    from pandas.core.groupby import Grouper
  File "/home/joker/.local/lib/python3.5/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.groupby import GroupBy  # noqa: F401
  File "/home/joker/.local/lib/python3.5/site-packages/pandas/core/groupby/groupby.py", line 37, in <module>
    from pandas.core.frame import DataFrame
  File "/home/joker/.local/lib/python3.5/site-packages/pandas/core/frame.py", line 96, in <module>
    from pandas.core.internals.construction import (
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 330, in __exit__
  File "<frozen importlib._bootstrap>", line 225, in _verbose_message
KeyboardInterrupt
