Traceback (most recent call last):
  File "models/main.py", line 8, in <module>
    import pandas as pd
  File "/home/joker/.local/lib/python3.5/site-packages/pandas/__init__.py", line 13, in <module>
    __import__(dependency)
  File "/home/joker/.local/lib/python3.5/site-packages/numpy/__init__.py", line 145, in <module>
    from . import lib
  File "/home/joker/.local/lib/python3.5/site-packages/numpy/lib/__init__.py", line 39, in <module>
    from .npyio import *
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 765, in get_code
  File "<frozen importlib._bootstrap_external>", line 476, in _compile_bytecode
KeyboardInterrupt
